name = "MyExample"
uuid = "8baa7302-5e80-4bd8-8d11-30cb2223af3f"
authors = ["Vijayamanikandan Vijayarangan <vvmk007@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
